-- NO_IMPORTS

BOSS_DIALOG = {
    boom={
        spawn={
            ref="vehicles\\warthog\\raids\\torres\\fuckemup",
            loc={
                x=54.33,
                y=3.33,
                z=32.51
            },
            seconds=10,
            played=false
        },
        health_bracket_98={
            ref="vehicles\\warthog\\raids\\torres\\getem",
            loc={
                x=54.33,
                y=3.33,
                z=32.51
            },
            seconds=9,
            played=false
        }
    },
    bewm={
        spawn={
            ref="vehicles\\warthog\\raids\\torres\\catchifcan",
            loc={
                x=54.33,
                y=3.33,
                z=32.51
            },
            seconds=10,
            played=false
        }
    },
    griswald={
        spawn={
            ref="vehicles\\warthog\\raids\\torres\\shame",
            loc={
                x=54.33,
                y=3.33,
                z=32.51
            },
            seconds=12,
            played=false
        },
        health_bracket_98 = {
            ref="vehicles\\warthog\\raids\\torres\\defected",
            loc={
                x=54.33,
                y=3.33,
                z=32.51
            },
            seconds=20,
            played=false
        },
        health_bracket_50={
            ref="vehicles\\warthog\\raids\\torres\\reasons",
            loc={
                x=54.33,
                y=3.33,
                z=32.51
            },
            seconds=16,
            played=false
        }
    },
    backdraft={
        spawn={
            ref="vehicles\\warthog\\raids\\torres\\scared",
            loc={
                x=54.33,
                y=3.33,
                z=32.51
            },
            seconds=8,
            played=false

        }
    },
    torres={
        spawn={
            ref="vehicles\\warthog\\raids\\torres\\fine",
            loc={
                x=54.33,
                y=3.33,
                z=32.51
            },
            seconds=8,
            played=false
        },
        savant_inbound={
            ref="vehicles\\warthog\\raids\\torres\\nodice",
            loc={
                x=54.33,
                y=3.33,
                z=32.51
            },
            seconds=20,
            played=false
        },
        savant_spawn={
            ref="vehicles\\warthog\\raids\\torres\\savantdeployed",
            loc={
                x=54.33,
                y=3.33,
                z=32.51
            },
            seconds=7,
            played=false
        },
        wipe={
            ref="vehicles\\warthog\\raids\\torres\\wipe",
            loc={
                x=54.33,
                y=3.33,
                z=32.51
            },
            seconds=60,
            played=false
        },
        health_bracket_98={
            ref="vehicles\\warthog\\raids\\torres\\hits",
            loc={
                x=54.33,
                y=3.33,
                z=32.51
            },
            seconds=10,
            played=false
        },
        health_bracket_90={
            ref="vehicles\\warthog\\raids\\torres\\lucky",
            loc={
                x=54.33,
                y=3.33,
                z=32.51
            },
            seconds=9,
            played=false
        },
        health_bracket_75={
            ref="vehicles\\warthog\\raids\\torres\\giveup",
            loc={
                x=54.33,
                y=3.33,
                z=32.51
            },
            seconds=14,
            played=false
        },
        health_bracket_50={
            ref="vehicles\\warthog\\raids\\torres\\runaway",
            loc={
                x=54.33,
                y=3.33,
                z=32.51
            },
            seconds=11,
            played=false
        },
        health_bracket_25={
            ref="vehicles\\warthog\\raids\\torres\\howlose",
            loc={
                x=54.33,
                y=3.33,
                z=32.51
            },
            seconds=9,
            played=false
        },
        death={
            ref="vehicles\\warthog\\raids\\torres\\accomplished",
            loc={
                x=54.33,
                y=3.33,
                z=32.51
            },
            seconds=60,
            played=false
        }
    }
}
